repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Find secrets hidden.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --fail --no-verification'
        language: system
        stages: ["pre-commit"]