name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Step 4: Code formatting checks with ruff and black
      - name: Run code formatting checks
        run: |
          pip install ruff black
          ruff check .
          black --check .

      # Step 5: Lint checks with ruff, flake8, pylint
      - name: Run lint checks
        run: |
          pip install flake8 pylint
          flake8 .
          pylint $(find . -name "*.py")

      # Step 6: Static Application Security Testing (SAST) with bandit
      - name: Run SAST
        run: |
          pip install bandit
          bandit -r .

      # Step 7: Secret Scanning with trufflehog
      - name: Run secret scanning
        uses: trufflesecurity/trufflehog@v4
        with:
          scan: true

      # Step 8: Run tests and generate coverage report
      - name: Run tests with pytest and generate coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=.

